
package BD_HAB_DES;

import BD_Docente.*;
import static BD_Reportes.ConsultarReporte.jtablahaber;
import Control_BD.*;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.awt.event.KeyAdapter;

/**
 *
 * @author Sergio
 */
public class Agregar_hab_des extends javax.swing.JDialog {
String iddocente="";
String fecha="";
 static public int idHaber_doc=0;
  static public int idDescu_doc=0;
    public database_haberes db = new database_haberes();
    public Object[][] dtPersona;
    
    private Descuentos.databaseDescuentos db2 = new Descuentos.databaseDescuentos();
    private Object[][] dtPersona2;

    /**
     * Creates new form ListarCliente
     */

            void  ocultar_columnas_docente() {
       jTableListarDocente.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableListarDocente.getColumnModel().getColumn(0).setMinWidth(0);
   jTableListarDocente.getColumnModel().getColumn(2).setMaxWidth(0);
        jTableListarDocente.getColumnModel().getColumn(2).setMinWidth(0);
            
    }
               void  tam_columnas_docente() {
                          int[] anchos = {0, 110, 0, 110, 50, 150, 250, 180, 180};
        for (int i = 0; i < jTableListarDocente.getColumnCount(); i++) {
            jTableListarDocente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
            
    } 
    public Agregar_hab_des(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
      Control_BD.Control_Docente load = new Control_Docente();
        load.CargarDocente_hab_des();
        ocultar_columnas_docente();
        tam_columnas_docente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogHaber = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnRegistrarHaber = new javax.swing.JButton();
        jLabel_i1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbox_HAB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMonto = new javax.swing.JTextField();
        jDialogDescuento = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldDni_desc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtnRegistrarDesc = new javax.swing.JButton();
        jLabel_i2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbox_DESC = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFecha_des = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldMonto_Des = new javax.swing.JTextField();
        Haberes_dialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label_nombre_dialog = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox_Haber = new javax.swing.JComboBox<>();
        Descuentos_dialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDescuentos = new javax.swing.JTable();
        label_nombre_dialog1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarDocente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel_i = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldParametroBusqueda = new javax.swing.JTextField();
        jLabel_docente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combofiltro = new javax.swing.JComboBox<>();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jButton_AddDescuento = new javax.swing.JButton();
        jButton_addHaberes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jDialogHaber.setMinimumSize(new java.awt.Dimension(500, 450));
        jDialogHaber.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(592, 300));

        jTextFieldDni.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldDni.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFieldDni.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDni.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dni");

        BtnRegistrarHaber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnRegistrarHaber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/guardar.png"))); // NOI18N
        BtnRegistrarHaber.setText("Regristar");
        BtnRegistrarHaber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarHaberActionPerformed(evt);
            }
        });

        jLabel_i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/school.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Asignar Haberes a Docente");

        cbox_HAB.setBackground(new java.awt.Color(0, 102, 255));
        cbox_HAB.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cbox_HAB.setForeground(new java.awt.Color(255, 153, 0));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Haber");

        jTextFieldFecha.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldFecha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto");

        jTextFieldMonto.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldMonto.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextFieldMonto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_i1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_HAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegistrarHaber)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addComponent(jLabel_i1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_HAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegistrarHaber)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jDialogHaber.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 490, 450));

        jDialogDescuento.setMinimumSize(new java.awt.Dimension(500, 450));
        jDialogDescuento.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(592, 300));

        jTextFieldDni_desc.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldDni_desc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFieldDni_desc.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDni_desc.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dni");

        BtnRegistrarDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnRegistrarDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/guardar.png"))); // NOI18N
        BtnRegistrarDesc.setText("Regristar");
        BtnRegistrarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarDescActionPerformed(evt);
            }
        });

        jLabel_i2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/school.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 0));
        jLabel17.setText("Asignar Descuentos a Docente");

        cbox_DESC.setBackground(new java.awt.Color(0, 102, 255));
        cbox_DESC.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cbox_DESC.setForeground(new java.awt.Color(255, 153, 0));
        cbox_DESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_DESCActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descuento");

        jTextFieldFecha_des.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldFecha_des.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextFieldFecha_des.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monto");

        jTextFieldMonto_Des.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldMonto_Des.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextFieldMonto_Des.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_i2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMonto_Des, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_DESC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDni_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFecha_des, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegistrarDesc)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addComponent(jLabel_i2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDni_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_DESC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldFecha_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldMonto_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegistrarDesc)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jDialogDescuento.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 490, 450));

        Haberes_dialog.setTitle("Haberes");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jTable1.setRowHeight(20);
        jScrollPane2.setViewportView(jTable1);

        label_nombre_dialog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_nombre_dialog.setForeground(new java.awt.Color(0, 0, 204));

        jButton1.setText("AGREGAR HABERES");

        javax.swing.GroupLayout Haberes_dialogLayout = new javax.swing.GroupLayout(Haberes_dialog.getContentPane());
        Haberes_dialog.getContentPane().setLayout(Haberes_dialogLayout);
        Haberes_dialogLayout.setHorizontalGroup(
            Haberes_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Haberes_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_nombre_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(Haberes_dialogLayout.createSequentialGroup()
                .addGroup(Haberes_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Haberes_dialogLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Haber, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Haberes_dialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        Haberes_dialogLayout.setVerticalGroup(
            Haberes_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Haberes_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombre_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(Haberes_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox_Haber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Descuentos_dialog.setTitle("Haberes");

        jTableDescuentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDescuentos.setRowHeight(20);
        jScrollPane3.setViewportView(jTableDescuentos);

        label_nombre_dialog1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_nombre_dialog1.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout Descuentos_dialogLayout = new javax.swing.GroupLayout(Descuentos_dialog.getContentPane());
        Descuentos_dialog.getContentPane().setLayout(Descuentos_dialogLayout);
        Descuentos_dialogLayout.setHorizontalGroup(
            Descuentos_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Descuentos_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Descuentos_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_nombre_dialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        Descuentos_dialogLayout.setVerticalGroup(
            Descuentos_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Descuentos_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombre_dialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Docente");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableListarDocente.setBackground(new java.awt.Color(0, 153, 204));
        jTableListarDocente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTableListarDocente.setForeground(new java.awt.Color(255, 255, 255));
        jTableListarDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarDocente.setGridColor(new java.awt.Color(255, 51, 0));
        jTableListarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarDocente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 170));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda (1).png"))); // NOI18N
        jLabel3.setText("Buscar ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/teacher.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione Docente");

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/error.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldParametroBusqueda.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldParametroBusqueda.setForeground(new java.awt.Color(255, 153, 0));
        jTextFieldParametroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldParametroBusquedaActionPerformed(evt);
            }
        });
        jTextFieldParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyTyped(evt);
            }
        });

        jLabel_docente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id Docente");

        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Periodo");

        combofiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "TIPO", "NOMBRE" }));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jButton_AddDescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AddDescuento.setForeground(new java.awt.Color(0, 51, 255));
        jButton_AddDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/order-192.png"))); // NOI18N
        jButton_AddDescuento.setText("Add Descuento");
        jButton_AddDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddDescuentoActionPerformed(evt);
            }
        });

        jButton_addHaberes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_addHaberes.setForeground(new java.awt.Color(0, 51, 255));
        jButton_addHaberes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/order-192.png"))); // NOI18N
        jButton_addHaberes.setText("Add Haber");
        jButton_addHaberes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addHaberesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Año");

        jDesktopPane1.setLayer(jLabel_i, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldParametroBusqueda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_docente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(combofiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_AddDescuento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_addHaberes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel_i)
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(combofiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_addHaberes)
                                    .addComponent(jButton_AddDescuento)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel_i))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combofiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addComponent(jButton_addHaberes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton_AddDescuento)
                .addGap(39, 39, 39)
                .addComponent(jButtonCancelar)
                .addGap(88, 88, 88))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1020, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void llamarhaber(){
     
  
        // llamada de datos
                //Control_Reportes cc = new Control_Reportes();
 System.out.println("recibiendo "+iddocente);
      jTextFieldDni.setText(iddocente);
             //Centramos nuestro jDialog
      
        Haberes_dialog.setLocation(200, 100);
        //La hacemos modal
        Haberes_dialog.setModal(true);
        //Establecemos dimensiones.
        Haberes_dialog.setMinimumSize(new Dimension(500, 450));
     
        //Establecemos un  para el jDialog
        Haberes_dialog.setTitle("Reporte.");
        //La hacemos visible.
        Haberes_dialog.setVisible(true);
        cargar_combo();

 }
  private void llamardescuento(){
     
  
        // llamada de datos
                //Control_Reportes cc = new Control_Reportes();
 System.out.println("recibiendo "+iddocente);
      jTextFieldDni_desc.setText(iddocente);
             //Centramos nuestro jDialog
        Descuentos_dialog.setLocation(200, 100);
        //La hacemos modal
        Descuentos_dialog.setModal(true);
        //Establecemos dimensiones.
        Descuentos_dialog.setMinimumSize(new Dimension(500, 450));
     
//       jLabel16.setText("Reporte planilla");
        //Establecemos un  para el jDialog
        Descuentos_dialog.setTitle("descuento.");
        //La hacemos visible.
        Descuentos_dialog.setVisible(true);
      //  cargar_combo();

 }
 public void cargar_combo()
 {
        ConexionConBaseDatos conectar = new ConexionConBaseDatos();
              Connection conexion = null;
    Statement sentencia = null;
    ResultSet resultado = null;
    PreparedStatement ps = null;
    
         try {
        jComboBox_Haber.removeAllItems();
  
        Statement st=conexion.createStatement();
        ResultSet rs=st.executeQuery("Select * from t_haberes");
        while(rs.next())
        {                
            jComboBox_Haber.addItem(rs.getString(""));


        }
    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(null,ex);
    } 
 }
    private void jTableListarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarDocenteMouseClicked
        // TODO add your handling code here:
        try {
                    int fila = jTableListarDocente.rowAtPoint(evt.getPoint());

       
        iddocente=(jTableListarDocente.getValueAt(fila, 0).toString());
       jLabel_docente.setText(jTableListarDocente.getValueAt(fila, 0).toString());
     label_nombre_dialog1.setText(jTableListarDocente.getValueAt(fila, 5).toString()+"  "+jTableListarDocente.getValueAt(fila, 6).toString()+"  "+jTableListarDocente.getValueAt(fila, 7).toString());
label_nombre_dialog.setText(jTableListarDocente.getValueAt(fila, 5).toString()+"  "+jTableListarDocente.getValueAt(fila, 6).toString()+"  "+jTableListarDocente.getValueAt(fila, 7).toString());
            
        } catch (Exception e) {
            System.out.println(e.getMessage());

            
            
        }

    }//GEN-LAST:event_jTableListarDocenteMouseClicked

     private void Actualizar_Tabla_descuentos(){
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"t_doc_desc" ,"DNI_DOC","ID_DES","DESCUENTO","MONTO","NOMBRE"};  
        String a = txt_fecha.getText()+'0'+(jComboBoxMes.getSelectedIndex()+1);
        db2.EnviarDatos(iddocente, a);
        dtPersona2 = db2.Select_Persona();
  
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtPersona2,columNames);
        jTableDescuentos.setModel(datos);
}
    private void BtnRegistrarHaberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarHaberActionPerformed
        // TODO add your handling code her
        //Control_BD.Control_EstablecimientoCargarGETestablecimiento();
        // obtener datos
System.out.println(idHaber_doc);
        if( jTextFieldDni.getText().isEmpty() || jTextFieldFecha.getText().isEmpty() || jTextFieldMonto.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "ALGUN CAMPO ESTA VACIO", "ERROR",
                JOptionPane.WARNING_MESSAGE);
        }
        else{
            Control_Doc_haberes c=new Control_Doc_haberes();
c.ejecutarGEThaber();
            int idha=0;
            idha=idHaber_doc+1;
            String dni=jTextFieldDni.getText();
           int id_hab = cbox_HAB.getSelectedIndex();
           String fecha=jTextFieldFecha.getText();
           String m= jTextFieldMonto.getText();
           double monto=Double.valueOf(m);
        //  m=m+1;
          //String anio=cbox_HAB.getSelectedItem().toString(); 
         // String mes=String.valueOf(m);
  id_hab=id_hab+1;
            Control_Doc_haberes.addHaberes(idha,dni,id_hab,fecha,monto);
            // codigo de introducir datos a la mysql
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(this,"Registrado CORRECTAMENTE","Registrado",JOptionPane.PLAIN_MESSAGE);
   jDialogHaber.dispose();
            


            //}
        }
    }//GEN-LAST:event_BtnRegistrarHaberActionPerformed

    private void BtnRegistrarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarDescActionPerformed
        // TODO add your handling code here:
        System.out.println(idDescu_doc);
        if( jTextFieldDni_desc.getText().isEmpty() || jTextFieldFecha_des.getText().isEmpty() || jTextFieldMonto_Des.getText().isEmpty()){

            JOptionPane.showMessageDialog(this, "ALGUN CAMPO ESTA VACIO", "ERROR",
                JOptionPane.WARNING_MESSAGE);
        }
        else{
            Control_Doc_descuentos c=new Control_Doc_descuentos();
c.ejecutarGETdescuento();

            int idha=0;
            idha=idDescu_doc+1;
            String dni=jTextFieldDni_desc.getText();
           int id_des = cbox_DESC.getSelectedIndex();
           String fecha=jTextFieldFecha_des.getText();
           String m= jTextFieldMonto_Des.getText();
           double monto=Double.valueOf(m);
           id_des=id_des+1;
        //  m=m+1;
          //String anio=cbox_HAB.getSelectedItem().toString(); 
         // String mes=String.valueOf(m);

            Control_Doc_descuentos.adddescuentos(idha,dni,id_des,fecha,monto);
            // codigo de introducir datos a la mysql
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(this,"Registrado CORRECTAMENTE","Registrado",JOptionPane.PLAIN_MESSAGE);
   jDialogDescuento.dispose();
            


            //}
        }
    }//GEN-LAST:event_BtnRegistrarDescActionPerformed

    private void cbox_DESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_DESCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_DESCActionPerformed

    private void jButton_addHaberesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addHaberesActionPerformed
        // TODO add your handling code here:
        // obtener datos

        if (txt_fecha.getText().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Ingrese una fecha");
        }else{
            if(jLabel_docente.getText().equals("") ){

                JOptionPane.showMessageDialog(rootPane, "Selecona un docente");
            }
            else
            {

                Actualizar_Tabla_haberes();
                //oculta columna ID
                jTable1.getColumnModel().getColumn(1).setMaxWidth(1);
                jTable1.getColumnModel().getColumn(1).setMinWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(1);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(1);
                jTable1.getColumnModel().getColumn(0).setMinWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(1);
                jTable1.getColumnModel().getColumn(2).setMaxWidth(1);
                jTable1.getColumnModel().getColumn(2).setMinWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(1);

                jTable1.getColumnModel().getColumn(5).setMaxWidth(1);
                jTable1.getColumnModel().getColumn(5).setMinWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(1);
                jTable1.getTableHeader().getColumnModel().getColumn(5).setMinWidth(1);

                //editor de caldas
                jTable1.getColumnModel().getColumn( 0 ).setCellEditor(new MyTableCellEditor_haberes(db,"id_hab_des"));
                jTable1.getColumnModel().getColumn( 1 ).setCellEditor(new MyTableCellEditor_haberes(db,"DNI_DOC"));
                jTable1.getColumnModel().getColumn( 2 ).setCellEditor(new MyTableCellEditor_haberes(db,"ID_HAB"));//Columna Nombre
                jTable1.getColumnModel().getColumn( 3 ).setCellEditor(new MyTableCellEditor_haberes(db,"NOMBRE_HAB"));//Columna Apellido
                jTable1.getColumnModel().getColumn( 4 ).setCellEditor(new MyTableCellEditor_haberes(db,"MONTO_HAB"));//Columna Edad
                jTable1.getColumnModel().getColumn( 5 ).setCellEditor(new MyTableCellEditor_haberes(db,"NOMBRE"));//Columna Edad
                //        jTable1.getColumnModel().getColumn( 6 ).setCellEditor(new MyTableCellEditor_haberes(db,"AP_MATERNO"));

                //Control_Docente change = new Control_Docente();

                //String iddoc=jLabel_docente.getText();
                //                   Control_Haberes C=new Control_Haberes();
                //   C.ejecutarGETcargarCOMBO();
                //        llamar_main_haber();
                llamarhaber();
            }
        }
    }//GEN-LAST:event_jButton_addHaberesActionPerformed

    private void jButton_AddDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddDescuentoActionPerformed
        // TODO add your handling code here:
        if(jLabel_docente.getText().equals("") ){

            JOptionPane.showMessageDialog(rootPane, "Selecona un docente");
        }
        else
        {

            // TODO add your handling code here:
            Actualizar_Tabla_descuentos();
            //oculta columna ID
            jTableDescuentos.getColumnModel().getColumn(1).setMaxWidth(1);
            jTableDescuentos.getColumnModel().getColumn(1).setMinWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(1).setMinWidth(1);
            jTableDescuentos.getColumnModel().getColumn(0).setMaxWidth(1);
            jTableDescuentos.getColumnModel().getColumn(0).setMinWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(1);
            jTableDescuentos.getColumnModel().getColumn(2).setMaxWidth(1);
            jTableDescuentos.getColumnModel().getColumn(2).setMinWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(2).setMinWidth(1);

            jTableDescuentos.getColumnModel().getColumn(5).setMaxWidth(1);
            jTableDescuentos.getColumnModel().getColumn(5).setMinWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(1);
            jTableDescuentos.getTableHeader().getColumnModel().getColumn(5).setMinWidth(1);

            //editor de caldas
            jTableDescuentos.getColumnModel().getColumn( 0 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"t_doc_desc"));
            jTableDescuentos.getColumnModel().getColumn( 1 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"DNI_DOC"));
            jTableDescuentos.getColumnModel().getColumn( 2 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"ID_DES"));//Columna Nombre
            jTableDescuentos.getColumnModel().getColumn( 3 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"NOMBRE_DESC"));//Columna Apellido
            jTableDescuentos.getColumnModel().getColumn( 4 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"MONTO_DES"));//Columna Edad
            jTableDescuentos.getColumnModel().getColumn( 5 ).setCellEditor(new Descuentos.MyTableCellEditor_Descuentos(db2,"NOMBRE"));//Columna Edad
            //        jTable1.getColumnModel().getColumn( 6 ).setCellEditor(new MyTableCellEditor_Descuentos(db,"AP_MATERNO"));
            //Control_Docente change = new Control_Docente();

            //String iddoc=jLabel_docente.getText();
            //                   Control_Descuentos C=new Control_Descuentos();
            //  C.ejecutarGETcargarCOMBO();
            llamardescuento();
        }
    }//GEN-LAST:event_jButton_AddDescuentoActionPerformed

    private void jTextFieldParametroBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyTyped
        // TODO add your handling code here:
        jTextFieldParametroBusqueda.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextFieldParametroBusqueda.getText());
                jTextFieldParametroBusqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(jTableListarDocente.getModel());
        jTableListarDocente.setRowSorter(trsFiltro);
    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyTyped

    private void jTextFieldParametroBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyPressed
        // TODO add your handling code here:
        /* Control_Docente cc = new Control_Docente();
        String parametroBusqueda = jTextFieldParametroBusqueda.getText();
        cc.buscarDocenteParahab_des(parametroBusqueda);
        int[] anchos = {35, 300, 50, 100, 100, 150,100, 300, 50};
        for (int i = 0; i < Agregar_hab_des.jTableListarDocente.getColumnCount(); i++) {
            Agregar_hab_des.jTableListarDocente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
        ocultar_columnas_docente();
        tam_columnas_docente();*/
    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyPressed

    private void jTextFieldParametroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParametroBusquedaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        System.gc();//limpiar basura
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed
    private TableRowSorter trsFiltro;
    public void filtro() {
        
        int columnaABuscar = 0;
        if (combofiltro.getSelectedItem() == "DNI") {
            columnaABuscar = 0;
        }
        if (combofiltro.getSelectedItem().toString() == "TIPO") {
            columnaABuscar = 3;
        }
        if (combofiltro.getSelectedItem() == "NOMBRE") {
            columnaABuscar = 5;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(jTextFieldParametroBusqueda.getText(), columnaABuscar));
    }
     private void Actualizar_Tabla_haberes(){
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"id_hab_des" ,"DNI_DOC","ID_HAB","HABERES","MONTO","NOMBRE"};  
        String a = txt_fecha.getText()+'0'+(jComboBoxMes.getSelectedIndex()+1);
        db.EnviarDatos(iddocente, a);
        dtPersona = db.Select_Persona();
  
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtPersona,columNames);
        jTable1.setModel(datos);
}
public void llamar_main_haber(){
             Actualizar_Tabla_haberes();
        //oculta columna ID
        jTable1.getColumnModel().getColumn(1).setMaxWidth(1);
        jTable1.getColumnModel().getColumn(1).setMinWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setMinWidth(1);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(1);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(1);
        jTable1.getColumnModel().getColumn(2).setMinWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(1);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setMinWidth(1);
        //editor de caldas
             jTable1.getColumnModel().getColumn( 0 ).setCellEditor(new MyTableCellEditor_haberes(db,"id_hab_des"));
              jTable1.getColumnModel().getColumn( 1 ).setCellEditor(new MyTableCellEditor_haberes(db,"DNI_DOC"));
        jTable1.getColumnModel().getColumn( 2 ).setCellEditor(new MyTableCellEditor_haberes(db,"ID_HAB"));//Columna Nombre
        jTable1.getColumnModel().getColumn( 3 ).setCellEditor(new MyTableCellEditor_haberes(db,"NOMBRE_HAB"));//Columna Apellido
        jTable1.getColumnModel().getColumn( 4 ).setCellEditor(new MyTableCellEditor_haberes(db,"MONTO_HAB"));//Columna Edad
jTable1.getColumnModel().getColumn( 5 ).setCellEditor(new MyTableCellEditor_haberes(db,"NOMBRE"));//Columna Edad      
//        jTable1.getColumnModel().getColumn( 6 ).setCellEditor(new MyTableCellEditor_haberes(db,"AP_MATERNO"));

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_hab_des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_hab_des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_hab_des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_hab_des.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar_hab_des dialog = new Agregar_hab_des(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                   
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarDesc;
    private javax.swing.JButton BtnRegistrarHaber;
    private javax.swing.JDialog Descuentos_dialog;
    private javax.swing.JDialog Haberes_dialog;
    public static javax.swing.JComboBox cbox_DESC;
    public static javax.swing.JComboBox cbox_HAB;
    private javax.swing.JComboBox<String> combofiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButton_AddDescuento;
    private javax.swing.JButton jButton_addHaberes;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBox_Haber;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogDescuento;
    private javax.swing.JDialog jDialogHaber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_docente;
    private javax.swing.JLabel jLabel_i;
    private javax.swing.JLabel jLabel_i1;
    private javax.swing.JLabel jLabel_i2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDescuentos;
    public static javax.swing.JTable jTableListarDocente;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldDni_desc;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFecha_des;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldMonto_Des;
    private javax.swing.JTextField jTextFieldParametroBusqueda;
    private javax.swing.JLabel label_nombre_dialog;
    private javax.swing.JLabel label_nombre_dialog1;
    private javax.swing.JTextField txt_fecha;
    // End of variables declaration//GEN-END:variables
}
