
package BD_Reportes;

import BD_Docente.*;
import BD_HAB_DES.AgregarHaberes;
import static BD_HAB_DES.AgregarHaberes.idHaber;
import Control_BD.*;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sergio
 */
public class ConsultarReporte extends javax.swing.JDialog {
String iddocente="";
int docente=0;
String mess="";
String anios="";
public static String nombre_docente;
public static double total_haberes=0;
public static double total_descuentos=0;
DefaultTableModel modelo;
    //vector con los titulos de cada columna
    // Conectar Base de Datos

    //haberes
    double SueldoBase=0;double Bonifpersonal=0;double TPhomF=0;double TPhumL=0;double Diferenc=0;double Familiar=0;double Refmov=0;double Encargos=0;
    double Contrato=0; double Bondir=0;double Ds021=0;double Aguinaldo=0;double Bespecifico=0;double Reunific=0;double Igv=0;double CTsca=0;double N172567119=0;
    double PRjuco=0;double Palmaju=0;double Gults=0;double L26504=0;double Cdeveng=0;double DL25897=0;double Palmamas=0;double Direc=0;
    //descuentos
    double N20530=0;double ONP=0;double IPssvida=0;;double Admin=0;double Magist=0;double Varios=0;double Capyup=0;double Judicial=0;double DL26897=0;double Zapateri=0;
    double Responsa=0;double Sesdis=0;double Bazares=0;double Multas=0;double Bmater=0;double Derese=0;double Subcafae=0;double Dea=0;double Sanpedro=0;double Ancije=0;
    double Sutage=0;double Rimacse=0;double Editoria=0;double Aceade=0;double Cafaecus=0;
    /**
     * Creates new form ListarCliente
     */
   
                                               void  ocultar_columnas_reportes() {
        jtablahaber.getColumnModel().getColumn(0).setMaxWidth(0);
        jtablahaber.getColumnModel().getColumn(0).setMinWidth(0);
          jtablaDescuento.getColumnModel().getColumn(0).setMaxWidth(0);
        jtablaDescuento.getColumnModel().getColumn(0).setMinWidth(0);
              
    }
                                                            void  tam_columnas_reportes() {
                          int[] anchos = {0, 200,200};
        for (int i = 0; i < jtablahaber.getColumnCount(); i++) {
            jtablahaber.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
        
        
                                int[] anchos2 = {0, 200,200};
        for (int j = 0; j < jtablaDescuento.getColumnCount(); j++) {
            jtablaDescuento.getColumnModel().getColumn(j).setPreferredWidth(anchos2[j]);}
            
    } 
        void  ocultar_columnas_docente() {
        jTableListar.getColumnModel().getColumn(1).setMaxWidth(0);
        jTableListar.getColumnModel().getColumn(1).setMinWidth(0);
   jTableListar.getColumnModel().getColumn(2).setMaxWidth(0);
        jTableListar.getColumnModel().getColumn(2).setMinWidth(0);
            
    }
               void  tam_columnas_docente() {
                          int[] anchos = {100, 0, 0, 50, 110, 150, 250, 180, 180};
        for (int i = 0; i < jTableListar.getColumnCount(); i++) {
            jTableListar.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
            
    } 
               
                

                           
        
        
    public ConsultarReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                 llamarDocente();
    //    jButtonBuscar_dni_nom.setEnabled(false);

        setLocationRelativeTo(null);
//      Control_BD.Control_Docente load = new Control_Docente();
    //    load.CargarDocenteconsultadocente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBoleta = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jButton_imprimir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablahaber = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtablaDescuento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel_docente = new javax.swing.JLabel();
        jLabel_total_descuento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_total_haber1 = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_total_total = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonCancelar = new javax.swing.JButton();
        jButtonBuscarentrefechas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel_i = new javax.swing.JLabel();
        jLabel_docente_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbox_mes = new javax.swing.JComboBox();
        cbox_anio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListar = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldParametroBusqueda1 = new javax.swing.JTextField();
        jButton_por_dni1 = new javax.swing.JButton();

        jDialogBoleta.setTitle("Docente");
        jDialogBoleta.setMinimumSize(new java.awt.Dimension(700, 500));
        jDialogBoleta.setPreferredSize(new java.awt.Dimension(700, 500));
        jDialogBoleta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialogBoleta.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane2.setBackground(new java.awt.Color(0, 102, 204));

        jButton_imprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda (1).png"))); // NOI18N
        jButton_imprimir.setText("Imprimir");
        jButton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimirActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DESCUENTOS");

        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtablahaber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtablahaber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jtablahaber);

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtablaDescuento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtablaDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(jtablaDescuento);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Haber");

        jLabel_docente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel_docente.setForeground(new java.awt.Color(255, 255, 153));
        jLabel_docente.setText("jLabel2");

        jLabel_total_descuento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel_total_descuento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_total_descuento.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("TOTAL");

        jLabel_total_haber1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel_total_haber1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_total_haber1.setText("jLabel2");

        jLabel_fecha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel_fecha.setForeground(new java.awt.Color(255, 255, 153));
        jLabel_fecha.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Descuento");

        jLabel_total_total.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel_total_total.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_total_total.setText("jLabel2");

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 0));
        jLabel20.setText("Generar Boleta de Pago");

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("HABERES");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel_total_haber1)))
                        .addGap(56, 56, 56)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_total_descuento))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel_total_total, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jButton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel_docente))
                        .addGap(74, 74, 74)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_fecha)
                            .addComponent(jLabel17))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel20)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_docente)
                    .addComponent(jLabel_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton_imprimir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_total_total)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_total_descuento)
                        .addComponent(jLabel4))
                    .addComponent(jLabel_total_haber1))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel20)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        jDesktopPane2.setLayer(jButton_imprimir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel_docente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel_total_descuento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel_total_haber1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel_fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel_total_total, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDialogBoleta.getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 490));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 51));
        jLabel21.setText("Buscar por nombre/ap-paterno");
        jDialogBoleta.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 15, 180, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Docente");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 380, 10));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte Boleta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 390, 50));

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 204));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/error.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonBuscarentrefechas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscarentrefechas.setForeground(new java.awt.Color(0, 153, 51));
        jButtonBuscarentrefechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report.png"))); // NOI18N
        jButtonBuscarentrefechas.setText("Boleta");
        jButtonBuscarentrefechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarentrefechasActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entre fechas");

        jLabel_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report.png"))); // NOI18N

        jLabel_docente_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_docente_id.setForeground(new java.awt.Color(51, 51, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        cbox_mes.setBackground(new java.awt.Color(0, 102, 255));
        cbox_mes.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cbox_mes.setForeground(new java.awt.Color(255, 153, 0));
        cbox_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));

        cbox_anio.setBackground(new java.awt.Color(0, 102, 255));
        cbox_anio.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        cbox_anio.setForeground(new java.awt.Color(255, 153, 0));
        cbox_anio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        cbox_anio.setSelectedIndex(17);

        jTableListar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListar.setGridColor(new java.awt.Color(0, 0, 0));
        jTableListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListar);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("Docentes");

        jTextFieldParametroBusqueda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldParametroBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldParametroBusqueda1ActionPerformed(evt);
            }
        });
        jTextFieldParametroBusqueda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusqueda1KeyPressed(evt);
            }
        });

        jButton_por_dni1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_por_dni1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda (1).png"))); // NOI18N
        jButton_por_dni1.setText("Buscar por dni");
        jButton_por_dni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_por_dni1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_i)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_docente_id, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6)
                                .addGap(45, 45, 45)
                                .addComponent(jButtonBuscarentrefechas))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(cbox_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(cbox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(238, 238, 238)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel18)
                        .addGap(96, 96, 96)
                        .addComponent(jTextFieldParametroBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_por_dni1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_docente_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_i))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBuscarentrefechas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(cbox_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(cbox_anio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_por_dni1)
                    .addComponent(jTextFieldParametroBusqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jDesktopPane1.setLayer(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonBuscarentrefechas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_i, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_docente_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cbox_mes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cbox_anio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldParametroBusqueda1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_por_dni1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 830, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void llamarDocente() {

        // llamada de datos
        Control_BD.Control_Docente load = new Control_Docente();
        load.CargarDocenteReporte();
        ocultar_columnas_docente();
                   tam_columnas_docente();
                  
    }


          
private void llamarReporte() {

        // llamada de datos
     
       // ocultar_columnas_reportes();
                //   tam_columnas_reportes();
                                           
  
        //Centramos nuestro jDialog
        jDialogBoleta.setLocation(200, 100);
        jLabel_docente.setText(nombre_docente);
        jLabel_fecha.setText(mess+" del "+anios);
        double total=0;
        total=total_haberes-total_descuentos;
        jLabel_total_total.setText(total+"");
              jLabel_total_haber1.setText(total_haberes+"");
                jLabel_total_descuento.setText(total_descuentos+"");
        jButton_imprimir.setVisible(true);
        jButton_imprimir.setLocation(600,100);
            jButton_imprimir.setMinimumSize(new Dimension(100, 50));
                  jPanel2.setVisible(true);
        jPanel2.setLocation(600,100);
            jPanel2.setMinimumSize(new Dimension(100, 50));
        //La hacemos modal
        jDialogBoleta.setModal(true);
        //Establecemos dimensiones.
        jDialogBoleta.setMinimumSize(new Dimension(700, 500));

        //Establecemos un título para el jDialog
        jDialogBoleta.setTitle("Lista de Docentes.");
        //La hacemos visible.
        jDialogBoleta.setVisible(true);
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        System.gc();//limpiar basura
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarentrefechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarentrefechasActionPerformed
// TODO add your handling code here:
        
          int i = jTableListar.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Favor... seleccione una docente");
         
        } 
        else{
    int n=0;
                 Control_Reportes cc = new Control_Reportes();
          int m = cbox_mes.getSelectedIndex();
          m=m+1;
          String anio=cbox_anio.getSelectedItem().toString(); 
          String mes=String.valueOf(m);
          if(mes.length()==1){
              mes="0"+mes;
          }
          
             mess =((String) cbox_mes.getItemAt(m-1));
        anios=anio;
          String getdni=iddocente;
     
     System.out.println(anio+mes);
 
       Control_BD.Control_Reportes load = new Control_Reportes();
        load.buscarReporteHaber(anio, mes, iddocente);
        load.buscarReporteDescuento(anio, mes, iddocente);
          llamarReporte();

              
     
            //}
        }
            
            
       

    }//GEN-LAST:event_jButtonBuscarentrefechasActionPerformed
public void Boleta(){
       // y ahora genera facturas guardada en la carpeta Facturas
       com.itextpdf.text.Image portada;

        // CREA DOCUMENTOS CON TAMAÑO CARTAS Y MARGENE DE TODO LADO DE 50   
        Document document = new Document(PageSize.LETTER, 50, 50, 50, 50);

        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("facturas/" + "reporte" + ".pdf"));
            document.open();

           // portada = Image.getInstance("portada.jpg");
            //portada.setAlignment(Element.ALIGN_CENTER);
            //portada.scalePercent(45f);// tamaño de imagen

            //document.add(portada);
            document.add(new Paragraph("            "+nombre_docente));
          
            document.add(new Paragraph("            "+mess+" del "+ anios));
            document.add(Chunk.NEWLINE);
     

double total=total_haberes-total_descuentos;
      
document.add(new Paragraph("          TOTAL -> HABERES-DESCUENTOS="+total +"" ));
      document.add(new Paragraph("          Total Haberes = "+total_haberes +"                                      "+"  Total Descuentos ="+total_descuentos));
          document.add(new Paragraph("       LISTA HABERES       "+ "                                     "+"   LISTA DESCUENTOS "));
         
         
     

            // parte de dibujo la tabla
            PdfContentByte cb = writer.getDirectContent();
          
            PdfTemplate tp = cb.createTemplate(500, 500);
           
            
      Graphics2D g ;
            Graphics2D g2 ;

            g2 = tp.createGraphicsShapes(500, 500);
 
    
            
             jtablahaber.print(g2);

       
            
            g2.dispose();
                 document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);


      
   
            document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);
            //posicion de la tabla de lista de compras

              cb.addTemplate(tp, 50,120);
              
              
                PdfContentByte cb1 = writer.getDirectContent();
                PdfTemplate tp1 = cb1.createTemplate(500, 500);
       g = tp1.createGraphicsShapes(500, 500);
         jtablaDescuento.print(g);
              g.dispose();
                    cb1.addTemplate(tp1, 320,120);
///            Paragraph parrafo = new Paragraph("RIchard quispe ");
   //         parrafo.setIndentationLeft(150);
            //parrafo.setInden(150)
      //      document.add(parrafo);
//                    document.add(new Paragraph(BOTTOM_ALIGNMENT, "RIchard quispe"));
                 // document.add(new Paragraph("            "+jTextFieldFecha.getText()+"                                      "+jTextFieldTotals.getText()));
            
            //cierra el documento
            document.close();
            JOptionPane.showMessageDialog(null, "Generado PDF Exitosamente.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
                      String file = new String("/facturas/" + "reporte" + ".pdf"); 
     String master = System.getProperty("user.dir") + file;
try {
     File path = new File (master);
     Desktop.getDesktop().open(path);
}catch (IOException ex) {
     ex.printStackTrace();
}
}
    private void jButton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimirActionPerformed
    Boleta();
    }//GEN-LAST:event_jButton_imprimirActionPerformed

    private void jTableListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarMouseClicked
        // TODO add your handling code here:
        try {
            int fila = jTableListar.rowAtPoint(evt.getPoint());

            iddocente=(jTableListar.getValueAt(fila, 0).toString());

   System.out.println(iddocente);
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jTableListarMouseClicked

    private void jTextFieldParametroBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusqueda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParametroBusqueda1ActionPerformed

    private void jTextFieldParametroBusqueda1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusqueda1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParametroBusqueda1KeyPressed

    private void jButton_por_dni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_por_dni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_por_dni1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarReporte dialog = new ConsultarReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                   
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbox_anio;
    private javax.swing.JComboBox cbox_mes;
    private javax.swing.JButton jButtonBuscarentrefechas;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_por_dni1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDialog jDialogBoleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_docente;
    private javax.swing.JLabel jLabel_docente_id;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_i;
    private javax.swing.JLabel jLabel_total_descuento;
    private javax.swing.JLabel jLabel_total_haber1;
    private javax.swing.JLabel jLabel_total_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableListar;
    private javax.swing.JTextField jTextFieldParametroBusqueda1;
    public static javax.swing.JTable jtablaDescuento;
    public static javax.swing.JTable jtablahaber;
    // End of variables declaration//GEN-END:variables
}
