package Descuentos;
import javax.swing.table.DefaultTableModel;
/**
*  @web http://blog.jheysonmatta.com.pe/
 * @author Jheyson Matta
 */
public class interfaz_Descuentos extends javax.swing.JFrame {

    private databaseDescuentos db2 = new databaseDescuentos();
    private Object[][] dtPersona2;

    /** Creates new form interfaz */
    public interfaz_Descuentos() {
        initComponents();
        this.setTitle(" descuentos");

   
    }
 

     private void Actualizar_Tabla_descuentos(){
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"t_doc_desc" ,"DNI_DOC","ID_DES","DESCUENTO","MONTO","NOMBRE"};        
        db2.EnviarDatos(txt_dni.getText(), txt_fecha.getText());
        dtPersona2 = db2.Select_Persona();
  
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtPersona2,columNames);
        jTableDescuentos.setModel(datos);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDescuentos = new javax.swing.JTable();
        txt_dni = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add_hab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDescuentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDescuentos);

        jLabel1.setText("dni");

        jLabel2.setText("Fecha");

        btn_add_hab.setText("Agregar");
        btn_add_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_habActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btn_add_hab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txt_fecha))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_add_hab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_habActionPerformed
        // TODO add your handling code here:
             Actualizar_Tabla_descuentos();
        //oculta columna ID
        jTableDescuentos.getColumnModel().getColumn(1).setMaxWidth(1);
        jTableDescuentos.getColumnModel().getColumn(1).setMinWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(1).setMinWidth(1);
        jTableDescuentos.getColumnModel().getColumn(0).setMaxWidth(1);
        jTableDescuentos.getColumnModel().getColumn(0).setMinWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(1);
        jTableDescuentos.getColumnModel().getColumn(2).setMaxWidth(1);
        jTableDescuentos.getColumnModel().getColumn(2).setMinWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(1);
        jTableDescuentos.getTableHeader().getColumnModel().getColumn(2).setMinWidth(1);
        //editor de caldas
             jTableDescuentos.getColumnModel().getColumn( 0 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"t_doc_desc"));
              jTableDescuentos.getColumnModel().getColumn( 1 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"DNI_DOC"));
        jTableDescuentos.getColumnModel().getColumn( 2 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"ID_DES"));//Columna Nombre
        jTableDescuentos.getColumnModel().getColumn( 3 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"NOMBRE_DESC"));//Columna Apellido
        jTableDescuentos.getColumnModel().getColumn( 4 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"MONTO_DES"));//Columna Edad
jTableDescuentos.getColumnModel().getColumn( 5 ).setCellEditor(new MyTableCellEditor_Descuentos(db2,"NOMBRE"));//Columna Edad      
//        jTable1.getColumnModel().getColumn( 6 ).setCellEditor(new MyTableCellEditor_Descuentos(db,"AP_MATERNO"));
    }//GEN-LAST:event_btn_add_habActionPerformed

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_Descuentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_hab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDescuentos;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_fecha;
    // End of variables declaration//GEN-END:variables

}
