
package BD_Establecimiento;

import Control_BD.Control_Establecimiento;
import BD_Docente.*;
import Control_BD.*;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;


/**
 *
 * @author Sergio
 */
public class ModificarEstablecimiento extends javax.swing.JDialog {
String idestablecimiento="";
    /**
     * Creates new form ListarCliente
     */

                void  ocultar_columnas_establecimiento() {
       jTableListarEstablecimiento.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableListarEstablecimiento.getColumnModel().getColumn(0).setMinWidth(0);

            
    }
               void  tam_columnas_establecimiento() {
                          int[] anchos = {0,200, 200, 200};
        for (int i = 0; i < jTableListarEstablecimiento.getColumnCount(); i++) {
            jTableListarEstablecimiento.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
            
    }
    public ModificarEstablecimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
      Control_BD.Control_Establecimiento load = new Control_Establecimiento();
        load.CargarDocenteconsultaReporteEstablecimiento();
        ocultar_columnas_establecimiento();
        tam_columnas_establecimiento(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogPlanilla = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablereporte_porestablec = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarEstablecimiento = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldParametroBusqueda = new javax.swing.JTextField();
        jLabel_i = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCodigoEstablecimiento = new javax.swing.JTextField();
        jTextFieldNombreEstableciento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSedeUgel = new javax.swing.JTextField();
        jButton_modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_IDestablecimiento = new javax.swing.JLabel();
        jButton_imprimir = new javax.swing.JButton();

        jDialogPlanilla.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Establecimientos");
        jDialogPlanilla.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtablereporte_porestablec.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtablereporte_porestablec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jtablereporte_porestablec);

        jDialogPlanilla.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 610, 230));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("Imprimir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialogPlanilla.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        jDialogPlanilla.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Establecimiento");
        setPreferredSize(new java.awt.Dimension(1103, 350));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione Establecimiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 570, 50));

        jTableListarEstablecimiento.setBackground(new java.awt.Color(0, 102, 153));
        jTableListarEstablecimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableListarEstablecimiento.setForeground(new java.awt.Color(255, 255, 255));
        jTableListarEstablecimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarEstablecimiento.setGridColor(new java.awt.Color(255, 0, 0));
        jTableListarEstablecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarEstablecimientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarEstablecimiento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 620, 170));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda (1).png"))); // NOI18N
        jLabel3.setText("Buscar ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 440, 10));

        jTextFieldParametroBusqueda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldParametroBusqueda.setForeground(new java.awt.Color(0, 0, 204));
        jTextFieldParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldParametroBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, 40));

        jLabel_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/school.png"))); // NOI18N
        jPanel1.add(jLabel_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo  establecimiento");

        jTextFieldCodigoEstablecimiento.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldCodigoEstablecimiento.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldCodigoEstablecimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoEstablecimientoKeyTyped(evt);
            }
        });

        jTextFieldNombreEstableciento.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldNombreEstableciento.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Establecimeinto");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sede Ugel");

        jTextFieldSedeUgel.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldSedeUgel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldSedeUgel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSedeUgelKeyTyped(evt);
            }
        });

        jButton_modificar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/guardar.png"))); // NOI18N
        jButton_modificar.setText("Modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/error.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IdEstablecimiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_IDestablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_modificar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreEstableciento)
                            .addComponent(jTextFieldSedeUgel)
                            .addComponent(jTextFieldCodigoEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCodigoEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNombreEstableciento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldSedeUgel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_IDestablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_modificar)
                    .addComponent(jButton2))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jButton_imprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print.png"))); // NOI18N
        jButton_imprimir.setText("Imprimir");
        jButton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void llamarplanilla(){
     
     
        // llamada de datos
                Control_Reportes cc = new Control_Reportes();
 System.out.println("recibiendo "+idestablecimiento);
        cc.buscarReportePorEstablecimientoPlanilla(idestablecimiento);
        int[] anchos = {100, 100, 100, 100, 100, 100,100, 100, 100};
        for (int i = 0; i < ModificarEstablecimiento.jtablereporte_porestablec.getColumnCount(); i++) {
            ModificarEstablecimiento.jtablereporte_porestablec.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
        //Centramos nuestro jDialog
        jDialogPlanilla.setLocation(200, 100);
        //La hacemos modal
        jDialogPlanilla.setModal(true);
        //Establecemos dimensiones.
        jDialogPlanilla.setMinimumSize(new Dimension(747, 385));
       jButton7.setText("Imprimir");
       jLabel16.setText("Reporte planilla");
        //Establecemos un  para el jDialog
        jDialogPlanilla.setTitle("Reporte.");
        //La hacemos visible.
        jDialogPlanilla.setVisible(true);
 
 }
    private void jButton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimirActionPerformed
        // TODO add your handling code here:
        // sale mensaje y decir que reporte es
        String reporte = JOptionPane.showInputDialog(null, "Escriba Titulo de la hoja?");
        // IMPRIMIR POR IMPRESORA
        try {
            //Mensaje de encabezado
            MessageFormat  headerFormat = new MessageFormat("Reportes de "+reporte);
            //Mensaje en el pie de pagina
            MessageFormat footerFormat = new MessageFormat("Lista de docentes");
            //Imprimir JTable
            jTableListarEstablecimiento.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        } catch (PrinterException ex) {
            Logger.getLogger(ModificarEstablecimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_imprimirActionPerformed

    private void jTextFieldParametroBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyPressed
        // TODO add your handling code here:
           Control_Establecimiento cc = new Control_Establecimiento();
        String parametroBusqueda = jTextFieldParametroBusqueda.getText();
        cc.buscarDocenteParaConsultaestalecimiento(parametroBusqueda);

            ocultar_columnas_establecimiento();
        tam_columnas_establecimiento(); 
    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyPressed

    private void jTableListarEstablecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarEstablecimientoMouseClicked
        // TODO add your handling code here:
        try {
                    int fila = jTableListarEstablecimiento.rowAtPoint(evt.getPoint());
                    
                        idestablecimiento=(jTableListarEstablecimiento.getValueAt(fila, 0).toString());
          jLabel_IDestablecimiento.setText((jTableListarEstablecimiento.getValueAt(fila, 0).toString()));
          jTextFieldCodigoEstablecimiento.setText((jTableListarEstablecimiento.getValueAt(fila, 1).toString()));
            jTextFieldNombreEstableciento.setText((jTableListarEstablecimiento.getValueAt(fila, 2).toString()));
        jTextFieldSedeUgel.setText((jTableListarEstablecimiento.getValueAt(fila, 3).toString()));

            
        } catch (Exception e) {
            System.out.println(e.getMessage());

            
            
        }

    }//GEN-LAST:event_jTableListarEstablecimientoMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String reporte = JOptionPane.showInputDialog(null, "Escriba Titulo de la hoja?");
        // IMPRIMIR POR IMPRESORA
        try {
            //Mensaje de encabezado
            MessageFormat  headerFormat = new MessageFormat("Reportes de "+reporte);
            //Mensaje en el pie de pagina
            MessageFormat footerFormat = new MessageFormat("Reporte");
            //Imprimir JTable
            jtablereporte_porestablec.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        } catch (PrinterException ex) {
            Logger.getLogger(ModificarEstablecimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogPlanilla.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldCodigoEstablecimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEstablecimientoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if( jTextFieldCodigoEstablecimiento.getText().length()== 8) {

            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldCodigoEstablecimientoKeyTyped

    private void jTextFieldSedeUgelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSedeUgelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

            //    Error.setText("Ingresa Solo Letras";

            }

    }//GEN-LAST:event_jTextFieldSedeUgelKeyTyped

    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
  
        if(jLabel_IDestablecimiento.getText().equals("") ){

          JOptionPane.showMessageDialog(rootPane, "Selecona un establecimiento");    
           }    
    else
    {
        Control_Establecimiento change = new Control_Establecimiento();
   
         String codesta= jTextFieldCodigoEstablecimiento.getText();
         String nomesta=   jTextFieldNombreEstableciento.getText();
        String sedeUgel= jTextFieldSedeUgel.getText();
        
        
        change.ModificarEstablecimiento(idestablecimiento, codesta, nomesta,sedeUgel);
          Control_BD.Control_Establecimiento load = new Control_Establecimiento();
        load.CargarDocenteconsultaReporteEstablecimiento();
            ocultar_columnas_establecimiento();
        tam_columnas_establecimiento(); 
            }     
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEstablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEstablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEstablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEstablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarEstablecimiento dialog = new ModificarEstablecimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                   
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JDialog jDialogPlanilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_IDestablecimiento;
    private javax.swing.JLabel jLabel_i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableListarEstablecimiento;
    private javax.swing.JTextField jTextFieldCodigoEstablecimiento;
    private javax.swing.JTextField jTextFieldNombreEstableciento;
    private javax.swing.JTextField jTextFieldParametroBusqueda;
    private javax.swing.JTextField jTextFieldSedeUgel;
    public static javax.swing.JTable jtablereporte_porestablec;
    // End of variables declaration//GEN-END:variables
}
