
package BD_Docente;

import static BD_Reportes.ConsultarReporte.jtablahaber;
import Control_BD.*;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;


/**
 *
 * @author Sergio
 */
public class ModificarDocente extends javax.swing.JDialog {
String iddocente="";
    /**
     * Creates new form ListarCliente
     */

            void  ocultar_columnas_docente() {
       jTableListarDocente.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableListarDocente.getColumnModel().getColumn(0).setMinWidth(0);
   jTableListarDocente.getColumnModel().getColumn(2).setMaxWidth(0);
        jTableListarDocente.getColumnModel().getColumn(2).setMinWidth(0);
            
    }
               void  tam_columnas_docente() {
                          int[] anchos = {0, 110, 0, 110, 50, 150, 250, 180, 180};
        for (int i = 0; i < jTableListarDocente.getColumnCount(); i++) {
            jTableListarDocente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
            
    } 
    public ModificarDocente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
      Control_BD.Control_Docente load = new Control_Docente();
        load.CargarDocenteconsultadocente();
        ocultar_columnas_docente();
        tam_columnas_docente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogPlanilla = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablereporte_pordocente = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarDocente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldCodmodular = new javax.swing.JTextField();
        jLabel_establecimiento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldCuentaBancaria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_ap_paterno = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_ap_materno = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_dni = new javax.swing.JTextField();
        jButton_modificar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_docente = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel_i = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton_imprimir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldParametroBusqueda = new javax.swing.JTextField();

        jDialogPlanilla.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Establecimientos");
        jDialogPlanilla.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtablereporte_pordocente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtablereporte_pordocente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jtablereporte_pordocente);

        jDialogPlanilla.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 610, 230));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("Imprimir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialogPlanilla.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        jDialogPlanilla.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Docente");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableListarDocente.setBackground(new java.awt.Color(0, 153, 204));
        jTableListarDocente.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTableListarDocente.setForeground(new java.awt.Color(255, 255, 255));
        jTableListarDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListarDocente.setGridColor(new java.awt.Color(255, 51, 0));
        jTableListarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarDocente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 170));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/busqueda (1).png"))); // NOI18N
        jLabel3.setText("Buscar ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo");

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cod. modular");

        jTextFieldCodmodular.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldCodmodular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCodmodular.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodmodular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodmodularKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodmodularKeyTyped(evt);
            }
        });

        jLabel_establecimiento.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cuenta Bancaria");

        jTextFieldTipo.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldTipo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldTipo.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldCuentaBancaria.setBackground(new java.awt.Color(0, 102, 153));
        jTextFieldCuentaBancaria.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldCuentaBancaria.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id Establecimiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCodmodular, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_establecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodmodular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_establecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 640, 190));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jTextField_nombre.setBackground(new java.awt.Color(0, 102, 153));
        jTextField_nombre.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextField_nombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nombre");

        jTextField_ap_paterno.setBackground(new java.awt.Color(0, 102, 153));
        jTextField_ap_paterno.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextField_ap_paterno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ap paterno");

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Ap materno");

        jTextField_ap_materno.setBackground(new java.awt.Color(0, 102, 153));
        jTextField_ap_materno.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextField_ap_materno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Dni");

        jTextField_dni.setBackground(new java.awt.Color(0, 102, 153));
        jTextField_dni.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextField_dni.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_dniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_dniKeyTyped(evt);
            }
        });

        jButton_modificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_modificar.setForeground(new java.awt.Color(0, 51, 255));
        jButton_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/guardar.png"))); // NOI18N
        jButton_modificar.setText("Modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });

        jButton_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_cancelar.setForeground(new java.awt.Color(0, 51, 255));
        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/error.png"))); // NOI18N
        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27))
                            .addComponent(jLabel28)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jTextField_ap_materno, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jTextField_nombre)
                    .addComponent(jTextField_ap_paterno))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cancelar)
                    .addComponent(jButton_modificar))
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_modificar)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_cancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ap_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ap_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id Docente");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 100, 20));

        jLabel_docente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 200, 25));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel_i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/teacher.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione Docente");

        jButton_imprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print.png"))); // NOI18N
        jButton_imprimir.setText("Imprimir");
        jButton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imprimirActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/error.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldParametroBusqueda.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jTextFieldParametroBusqueda.setForeground(new java.awt.Color(255, 153, 0));
        jTextFieldParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel_i)
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_imprimir))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(706, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel_i)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addGap(86, 86, 86))
        );
        jDesktopPane1.setLayer(jLabel_i, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_imprimir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldParametroBusqueda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1300, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        System.gc();//limpiar basura
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
 private void llamarplanilla(){
     
     
        // llamada de datos
                Control_Reportes cc = new Control_Reportes();
 System.out.println("recibiendo "+iddocente);
        cc.buscarReportePorDocentePlanilla(iddocente);
        int[] anchos = {100, 100, 100, 100, 100, 100,100, 100, 100};
        for (int i = 0; i < ModificarDocente.jtablereporte_pordocente.getColumnCount(); i++) {
            ModificarDocente.jtablereporte_pordocente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
        //Centramos nuestro jDialog
        jDialogPlanilla.setLocation(200, 100);
        //La hacemos modal
        jDialogPlanilla.setModal(true);
        //Establecemos dimensiones.
        jDialogPlanilla.setMinimumSize(new Dimension(747, 385));
       jButton7.setText("Imprimir");
       jLabel16.setText("Reporte planilla");
        //Establecemos un  para el jDialog
        jDialogPlanilla.setTitle("Reporte.");
        //La hacemos visible.
        jDialogPlanilla.setVisible(true);
 
 }
    private void jButton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imprimirActionPerformed
        // TODO add your handling code here:
        // sale mensaje y decir que reporte es
        String reporte = JOptionPane.showInputDialog(null, "Escriba Titulo de la hoja?");
        // IMPRIMIR POR IMPRESORA
        try {
            //Mensaje de encabezado
            MessageFormat  headerFormat = new MessageFormat("Reportes de "+reporte);
            //Mensaje en el pie de pagina
            MessageFormat footerFormat = new MessageFormat("Lista de docentes");
            //Imprimir JTable
            jTableListarDocente.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        } catch (PrinterException ex) {
            Logger.getLogger(ModificarDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_imprimirActionPerformed

    private void jTextFieldParametroBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyPressed
        // TODO add your handling code here:
           Control_Docente cc = new Control_Docente();
        String parametroBusqueda = jTextFieldParametroBusqueda.getText();
        cc.buscarDocenteParaConsultadocente(parametroBusqueda);
        int[] anchos = {35, 300, 50, 100, 100, 150,100, 300, 50};
        for (int i = 0; i < BD_Docente.ModificarDocente.jTableListarDocente.getColumnCount(); i++) {
            BD_Docente.ModificarDocente.jTableListarDocente.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);}
           ocultar_columnas_docente();
        tam_columnas_docente();
    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyPressed

    private void jTableListarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarDocenteMouseClicked
        // TODO add your handling code here:
        try {
                    int fila = jTableListarDocente.rowAtPoint(evt.getPoint());

       
       // iddocente=(jTableListarDocente.getValueAt(fila, 0).toString());
       jLabel_docente.setText(jTableListarDocente.getValueAt(fila, 0).toString());
          jTextField_dni.setText((jTableListarDocente.getValueAt(fila, 0).toString()));
            jLabel_establecimiento.setText((jTableListarDocente.getValueAt(fila, 1).toString()));
        jTextFieldCodmodular.setText((jTableListarDocente.getValueAt(fila, 2).toString()));
         jTextFieldTipo.setText((jTableListarDocente.getValueAt(fila, 3).toString()));
        jTextFieldCuentaBancaria.setText((jTableListarDocente.getValueAt(fila, 4).toString()));   
        jTextField_nombre.setText((jTableListarDocente.getValueAt(fila, 5).toString()));
        jTextField_ap_materno.setText((jTableListarDocente.getValueAt(fila, 6).toString()));
        jTextField_ap_paterno.setText((jTableListarDocente.getValueAt(fila, 7).toString()));
      
        

            
        } catch (Exception e) {
            System.out.println(e.getMessage());

            
            
        }

    }//GEN-LAST:event_jTableListarDocenteMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String reporte = JOptionPane.showInputDialog(null, "Escriba Titulo de la hoja?");
        // IMPRIMIR POR IMPRESORA
        try {
            //Mensaje de encabezado
            MessageFormat  headerFormat = new MessageFormat("Reportes de "+reporte);
            //Mensaje en el pie de pagina
            MessageFormat footerFormat = new MessageFormat("Reporte");
            //Imprimir JTable
            jtablereporte_pordocente.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        } catch (PrinterException ex) {
            Logger.getLogger(ModificarDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogPlanilla.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldCodmodularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodmodularKeyPressed
        // TODO add your handling code here:
   /*     if (jTextField_dni.getText().length()>= 9){
            String ruc="";
            ruc=jTextField_dni.getText();
            jTextField_dni.setText(ruc.substring(0, ruc.length()-1));}
        char c=evt.getKeyChar();
        //             String ruc=jTextField_rucKeyTyped(evt);.getText();

        if(Character.isLetter(c)) {

            getToolkit().beep();

            evt.consume();
        }*/
    }//GEN-LAST:event_jTextFieldCodmodularKeyPressed

    private void jTextFieldCodmodularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodmodularKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || jTextFieldCodmodular.getText().length()== 8) {

            getToolkit().beep();

            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldCodmodularKeyTyped

    private void jTextField_dniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_dniKeyPressed
        // TODO add your handling code here:
        /*   if (jTextField_dni.getText().length()>= 8){
            String ruc="";
            ruc=jTextField_dni.getText();
            jTextField_dni.setText(ruc.substring(0, ruc.length()-1));}
        char c=evt.getKeyChar();
        //             String ruc=jTextField_rucKeyTyped(evt);.getText();

        if(Character.isLetter(c)) {

            getToolkit().beep();

            evt.consume();
        }*/
        //   if (jTextField_dni.getText().length()== 8){

            // evt.consume();}
    }//GEN-LAST:event_jTextField_dniKeyPressed

    private void jTextField_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_dniKeyTyped
        // TODO add your handling code here:
        // int limite  = 8;
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || jTextField_dni.getText().length()== 8) {

            getToolkit().beep();

            evt.consume();
        }

    }//GEN-LAST:event_jTextField_dniKeyTyped

    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        // TODO add your handling code here:
        // obtener datos
    if(jLabel_docente.getText().equals("") ){

          JOptionPane.showMessageDialog(rootPane, "Selecona un docente");    
           }    
    else
    {
            Control_Docente change = new Control_Docente();
        
     //   String code = jTextField_busqueda.getText();
      
                   
   
       String iddoc=jLabel_docente.getText();
       String dni=   jTextField_dni.getText();
       String idestable=     jLabel_establecimiento.getText();
       String codmodula= jTextFieldCodmodular.getText();
        String tipo=   jTextFieldTipo.getText();
         String cuentaban= jTextFieldCuentaBancaria.getText();   
         String nombre= jTextField_nombre.getText();
         String apaterno= jTextField_ap_materno.getText();
        String amaterno=jTextField_ap_paterno.getText();
        
        
        change.ModificarDocente( dni, idestable,codmodula,tipo,cuentaban,nombre,apaterno,amaterno);
        
              Control_BD.Control_Docente load = new Control_Docente();
        load.CargarDocenteconsultadocente();
        ocultar_columnas_docente();
        tam_columnas_docente();
    }
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarDocente dialog = new ModificarDocente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                   
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_imprimir;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogPlanilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_docente;
    private javax.swing.JLabel jLabel_establecimiento;
    private javax.swing.JLabel jLabel_i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableListarDocente;
    private javax.swing.JTextField jTextFieldCodmodular;
    private javax.swing.JTextField jTextFieldCuentaBancaria;
    private javax.swing.JTextField jTextFieldParametroBusqueda;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextField_ap_materno;
    private javax.swing.JTextField jTextField_ap_paterno;
    private javax.swing.JTextField jTextField_dni;
    private javax.swing.JTextField jTextField_nombre;
    public static javax.swing.JTable jtablereporte_pordocente;
    // End of variables declaration//GEN-END:variables
}
